name: Release

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, mac]
        arch: [amd64, arm64]
        exclude:
          - os: mac
            arch: arm64
          - os: windows
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Specify the desired Go version here

      - name: Build for ${{ matrix.os }}/${{ matrix.arch }}
        run: go build -o harness_{{ matrix.os }}_${{ matrix.arch }} -v

      - name: Create release directory
        run: mkdir release

      - name: Copy binary to release directory
        run: cp harness_${{ matrix.os }}_${{ matrix.arch }} release/

      - name: Copy install script to release directory
        run: cp install_scripts/${{ matrix.os }}/install release/

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Create artifact
        run: zip -r release.zip release/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: harness-release
          path: release.zip
