name: Release

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, mac]
        arch: [amd64, arm64]
        exclude:
          - os: mac
            arch: arm64
          - os: windows
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Specify the desired Go version here

      - name: Build for ${{ matrix.os }}/${{ matrix.arch }}
        run: go build -o harness_${{ matrix.os }}_${{ matrix.arch }} -v

      - name: Create release directory
        run: mkdir -p ${{ github.workspace }}/release

      - name: Copy binary to release directory
        run: cp harness_${{ matrix.os }}_${{ matrix.arch }} ${{ github.workspace }}/release/

      - name: Copy install script to release directory
        run: cp install_scripts/${{ matrix.os }}/* ${{ github.workspace }}/release/
      - name: Current working dir is
        run: pwd
      - name: list release
        run: ls
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: harness-cli-release
          path: release.tar.gz


  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Create artifact
        uses: actions/download-artifact@v2
        with:
          name: harness-cli-release
          path: release.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: harness-release
          path: release.tar.gz
      - name: Perform Release
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          version=$(echo "${{ github.ref }}" | cut -d / -f 3)-${{ needs.build.outputs.commit }}
          gh release create $version --title "Version $version" --notes "Release notes" -R owner/repo
          gh release upload $version release.tar.gz -R owner/repo
          echo "Release completed"

        

